package ubuntu_test

import (
	"log/slog"
	"testing"

	"github.com/google/go-cmp/cmp"
	apiv2 "github.com/metal-stack/api/go/metalstack/api/v2"
	"github.com/metal-stack/os-installer/pkg/exec"
	oscommon "github.com/metal-stack/os-installer/pkg/installer/os/common"
	"github.com/metal-stack/os-installer/pkg/installer/os/ubuntu"
	"github.com/metal-stack/os-installer/pkg/test"
	"github.com/spf13/afero"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestDefaultOS_WriteHosts(t *testing.T) {
	tests := []struct {
		name       string
		allocation *apiv2.MachineAllocation
		fsMocks    func(fs *afero.Afero)
		want       string
		wantErr    error
	}{
		{
			name: "write hosts",
			allocation: &apiv2.MachineAllocation{
				Hostname: "my-host",
				Project:  "project-a",
				Networks: []*apiv2.MachineNetwork{
					{
						Network:     "379d294d-22e8-4aed-82e1-62c6c2f08d6a",
						Project:     new("project-a"),
						NetworkType: apiv2.NetworkType_NETWORK_TYPE_CHILD,
						Prefixes:    []string{"10.0.16.0/22"},
						Ips:         []string{"10.0.16.2"},
						Vrf:         3981,
						Asn:         4200003073,
					},
				},
			},
			want: `# this file was auto generated by the os-installer
127.0.0.1        localhost
10.0.16.2        my-host
`,
			wantErr: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var (
				log = slog.Default()
				fs  = &afero.Afero{
					Fs: afero.NewMemMapFs(),
				}
			)

			if tt.fsMocks != nil {
				tt.fsMocks(fs)
			}

			d := ubuntu.New(&oscommon.Config{
				Log:        log,
				Fs:         fs,
				Allocation: tt.allocation,
				Exec:       exec.New(log).WithCommandFn(test.FakeCmd(t)),
			})

			gotErr := d.WriteHosts(t.Context())
			if diff := cmp.Diff(tt.wantErr, gotErr, test.ErrorStringComparer()); diff != "" {
				t.Errorf("error diff (+got -want):\n%s", diff)
			}

			if tt.wantErr != nil {
				return
			}

			content, err := fs.ReadFile(oscommon.EtcHostsPath)
			require.NoError(t, err)

			assert.Equal(t, tt.want, string(content))
		})
	}
}
