package nftables

import (
	"context"
	"fmt"
	"log/slog"
	"net/netip"
	"strconv"
	"strings"

	"github.com/metal-stack/api/go/enum"
	apiv2 "github.com/metal-stack/api/go/metalstack/api/v2"
	"github.com/metal-stack/os-installer/old/exec"
	"github.com/metal-stack/os-installer/pkg/network"
	systemd_renderer "github.com/metal-stack/os-installer/pkg/systemd-service-renderer"
	renderer "github.com/metal-stack/os-installer/pkg/template-renderer"
	"github.com/spf13/afero"

	_ "embed"
)

const (
	serviceName     = "nftables.service"
	serviceUnitPath = "/etc/systemd/system/" + serviceName

	nftrulesPath = "/etc/nftables/rules"

	// Set up additional conntrack zone for DNS traffic.
	// There was a problem that duplicate packets were registered by conntrack
	// when packet was leaking from private VRF to the internet VRF.
	// Isolating traffic to special zone solves the problem.
	// Zone number(3) was obtained by experiments.
	dnsProxyZone = "3"

	dnsPort      = "domain"
	systemctlBin = "/bin/systemctl"

	// ForwardPolicyDrop drops packets which try to go through the forwarding chain
	ForwardPolicyDrop = ForwardPolicy("drop")
	// ForwardPolicyAccept accepts packets which try to go through the forwarding chain
	ForwardPolicyAccept = ForwardPolicy("accept")
)

var (
	//go:embed nftrules.tpl
	templateString string
)

type (
	Config struct {
		Log    *slog.Logger
		Reload bool

		Network *network.Network

		// FIXME validator net.Validator,
		EnableDNSProxy bool
		ForwardPolicy  ForwardPolicy

		fs afero.Fs
	}

	// ForwardPolicy defines how packets in the forwarding chain are handled, can be either drop or accept.
	// drop will be the standard for firewalls which are not managed by kubernetes resources (CWNPs)
	ForwardPolicy string

	// NftablesData represents the information required to render nftables configuration.
	NftablesData struct {
		Comment       string
		SNAT          []SNAT
		DNSProxyDNAT  DNAT
		VPN           bool
		ForwardPolicy string
		FirewallRules *FirewallRules
		Input         Input
	}

	Input struct {
		InInterfaces []string
	}

	FirewallRules struct {
		Egress  []string
		Ingress []string
	}

	// SNAT holds the information required to configure Source NAT.
	SNAT struct {
		Comment      string
		OutInterface string
		OutIntSpec   AddrSpec
		SourceSpecs  []AddrSpec
	}

	// DNAT holds the information required to configure DNAT.
	DNAT struct {
		Comment      string
		InInterfaces []string
		SAddr        string
		DAddr        string
		Port         string
		Zone         string
		DestSpec     AddrSpec
	}

	AddrSpec struct {
		AddressFamily string
		Address       string
	}

	// NftablesValidator can validate configuration for nftables rules.
	NftablesValidator struct {
		path string
		log  *slog.Logger
	}

	NftablesReloader struct{}
)

// Renders renders nftables rules according to the given input data and reloads the service if necessary
func Render(ctx context.Context, cfg *Config) (changed bool, err error) {
	const comment = "generated by os-installer"

	snat, err := getSNAT(cfg)
	if err != nil {
		return false, err
	}

	firewallRules, err := getFirewallRules(cfg)
	if err != nil {
		return false, err
	}

	data := NftablesData{
		Comment:       comment,
		SNAT:          snat,
		ForwardPolicy: string(cfg.ForwardPolicy),
		FirewallRules: firewallRules,
		Input:         getInput(cfg),
		VPN:           cfg.Network.HasVpn(),
	}

	if cfg.EnableDNSProxy {
		data.DNSProxyDNAT = getDNSProxyDNAT(cfg)
	}

	r, err := renderer.New(&renderer.Config{
		Log:            cfg.Log,
		TemplateString: templateString,
		Data:           data,
		Fs:             cfg.fs,
	})
	if err != nil {
		return false, err
	}

	changed, err = r.Render(ctx, nftrulesPath)
	if err != nil {
		return changed, err
	}

	// FIXME validate generated rule file before reloading

	if cfg.Reload && changed {
		if err := systemd_renderer.Reload(ctx, cfg.Log, serviceName); err != nil {
			return changed, err
		}
	}

	return
}

func getInput(cfg *Config) Input {
	input := Input{}
	for _, n := range cfg.Network.AllocationNetworks() {
		switch n.NetworkType {
		case apiv2.NetworkType_NETWORK_TYPE_CHILD, apiv2.NetworkType_NETWORK_TYPE_CHILD_SHARED:
			input.InInterfaces = append(input.InInterfaces, fmt.Sprintf("vrf%d", n.Vrf))
		}
	}
	return input
}

func getSNAT(cfg *Config) ([]SNAT, error) {
	var (
		result         []SNAT
		defaultNetwork *apiv2.MachineNetwork
		defaultAF      string
	)

	defaultNetwork, err := cfg.Network.GetDefaultRouteNetwork()
	if err != nil {
		return nil, err
	}
	defaultNetworkName := fmt.Sprintf("vrf%d", defaultNetwork.Vrf)

	ip, _ := netip.ParseAddr(defaultNetwork.Ips[0])
	defaultAF = "ip"
	if ip.Is6() {
		defaultAF = "ip6"
	}

	privatePrimaryPrefixes, err := cfg.Network.PrivatePrimaryNetworksPrefixes()
	if err != nil {
		return nil, err
	}

	for _, n := range cfg.Network.AllocationNetworks() {
		switch n.NetworkType {
		case apiv2.NetworkType_NETWORK_TYPE_UNDERLAY, apiv2.NetworkType_NETWORK_TYPE_SUPER, apiv2.NetworkType_NETWORK_TYPE_SUPER_NAMESPACED:
			continue
		}

		if n.NatType != apiv2.NATType_NAT_TYPE_IPV4_MASQUERADE {
			continue
		}

		cfg.Log.Info("getSNAT", "network", n.Network)
		var (
			sources []AddrSpec
			cmt     = fmt.Sprintf("snat (networkid: %s)", n.Network)
			svi     = fmt.Sprintf("vlan%d", n.Vrf)
			vrf     = fmt.Sprintf("vrf%d", n.Vrf)
		)

		for _, pfx := range privatePrimaryPrefixes {
			af, err := getAddressFamily(pfx)
			if err != nil {
				return nil, fmt.Errorf("unable to determine address family: %w", err)
			}

			sources = append(sources, AddrSpec{
				Address:       pfx,
				AddressFamily: af,
			})
			cfg.Log.Info("getSNAT", "network", n.Network, "prefixes", pfx, "af", af)
		}

		s := SNAT{
			Comment:      cmt,
			OutInterface: svi,
			SourceSpecs:  sources,
		}

		if cfg.EnableDNSProxy && (vrf == defaultNetworkName) {
			s.OutIntSpec = AddrSpec{
				AddressFamily: defaultAF,
				Address:       defaultNetwork.Ips[0],
			}
		}

		result = append(result, s)
	}

	return result, nil
}

func getDNSProxyDNAT(cfg *Config) DNAT {
	svis := []string{}
	for _, n := range cfg.Network.AllocationNetworks() {
		switch n.NetworkType {
		case apiv2.NetworkType_NETWORK_TYPE_CHILD, apiv2.NetworkType_NETWORK_TYPE_CHILD_SHARED:
			svi := fmt.Sprintf("vlan%d", n.Vrf)
			svis = append(svis, svi)
		}

	}

	n, err := cfg.Network.GetDefaultRouteNetwork()
	if err != nil {
		return DNAT{}
	}

	ip, _ := netip.ParseAddr(n.Ips[0])
	af := "ip"
	saddr := "10.0.0.0/8"
	daddr := "@proxy_dns_servers"
	if ip.Is6() {
		af = "ip6"
		saddr = "fd00::/8"
		daddr = "@proxy_dns_servers_v6"
	}
	return DNAT{
		Comment:      "dnat to dns proxy",
		InInterfaces: svis,
		SAddr:        saddr,
		DAddr:        daddr,
		Port:         dnsPort,
		Zone:         dnsProxyZone,
		DestSpec: AddrSpec{
			AddressFamily: af,
			Address:       n.Ips[0],
		},
	}
}

func getFirewallRules(cfg *Config) (*FirewallRules, error) {
	if cfg.Network.FirewallRules() == nil {
		return &FirewallRules{}, nil
	}
	var (
		egressRules           = []string{"# egress rules specified during firewall creation"}
		ingressRules          = []string{"# ingress rules specified during firewall creation"}
		inputInterfaces       = getInput(cfg)
		quotedInputInterfaces []string
	)
	for _, i := range inputInterfaces.InInterfaces {
		quotedInputInterfaces = append(quotedInputInterfaces, "\""+i+"\"")
	}

	for _, r := range cfg.Network.FirewallRules().Egress {
		ports := make([]string, len(r.Ports))
		for i, v := range r.Ports {
			ports[i] = strconv.Itoa(int(v))
		}
		for _, daddr := range r.To {
			af, err := getAddressFamily(daddr)
			if err != nil {
				return nil, err
			}
			protocolString, err := enum.GetStringValue(r.Protocol)
			if err != nil {
				return nil, err
			}
			egressRules = append(egressRules,
				fmt.Sprintf("iifname { %s } %s daddr %s %s dport { %s } counter accept comment %q", strings.Join(quotedInputInterfaces, ","), af, daddr, strings.ToLower(*protocolString), strings.Join(ports, ","), r.Comment))
		}
	}

	privatePrimaryNetwork, err := cfg.Network.PrivatePrimaryNetwork()
	if err != nil {
		return nil, err
	}
	outputInterfacenames := fmt.Sprintf("oifname { \"vrf%d\", \"vni%d\", \"vlan%d\" }", privatePrimaryNetwork.Vrf, privatePrimaryNetwork.Vrf, privatePrimaryNetwork.Vrf)

	for _, r := range cfg.Network.FirewallRules().Ingress {
		ports := make([]string, len(r.Ports))
		for i, v := range r.Ports {
			ports[i] = strconv.Itoa(int(v))
		}
		destinationSpec := ""
		if len(r.To) > 0 {
			af, err := getAddressFamily(r.To[0]) // To is validated to contain no mixed addressfamilies in metal-api
			if err != nil {
				continue
			}
			destinationSpec = fmt.Sprintf("%s daddr { %s }", af, strings.Join(r.To, ", "))
		} else if outputInterfacenames != "" {
			destinationSpec = outputInterfacenames
		} else {
			cfg.Log.Warn("no to address specified but not private primary network present, skipping this rule", "rule", r)
			continue
		}

		for _, saddr := range r.From {
			af, err := getAddressFamily(saddr)
			if err != nil {
				return nil, err
			}
			protocolString, err := enum.GetStringValue(r.Protocol)
			if err != nil {
				return nil, err
			}
			ingressRules = append(ingressRules, fmt.Sprintf("%s %s saddr %s %s dport { %s } counter accept comment %q", destinationSpec, af, saddr, strings.ToLower(*protocolString), strings.Join(ports, ","), r.Comment))
		}
	}
	return &FirewallRules{
		Egress:  egressRules,
		Ingress: ingressRules,
	}, nil
}

func getAddressFamily(p string) (string, error) {
	prefix, err := netip.ParsePrefix(p)
	if err != nil {
		return "", err
	}

	family := "ip"
	if prefix.Addr().Is6() {
		family = "ip6"
	}

	return family, nil
}

// Validate validates network interfaces configuration.
func (v NftablesValidator) Validate() error {
	v.log.Info("running 'nft --check --file' to validate changes.", "file", v.path)
	return exec.NewVerboseCmd("nft", "--check", "--file", v.path).Run()
}
