package interfaces

import (
	"context"
	"embed"
	_ "embed"
	"fmt"
	"log/slog"
	"path"

	apiv2 "github.com/metal-stack/api/go/metalstack/api/v2"
	"github.com/metal-stack/os-installer/pkg/network"
	renderer "github.com/metal-stack/os-installer/pkg/template-renderer"
	"github.com/spf13/afero"
)

const (
	systemdNetworkPath = "/etc/systemd/network/"

	loNetwork  interfaceKind = "lo.network.tpl"
	lanLink    interfaceKind = "lan.link.tpl"
	lanNetwork interfaceKind = "lan.network.tpl"

	bridgeNetwork interfaceKind = "bridge.network.tpl"
	bridgeNetdev  interfaceKind = "bridge.netdev.tpl"

	sviNetwork   interfaceKind = "svi.network.tpl"
	sviNetdev    interfaceKind = "svi.netdev.tpl"
	vrfNetwork   interfaceKind = "vrf.network.tpl"
	vrfNetdev    interfaceKind = "vrf.netdev.tpl"
	vxlanNetwork interfaceKind = "vxlan.network.tpl"
	vxlanNetdev  interfaceKind = "vxlan.netdev.tpl"

	comment = "generated by os-installer"
)

var (
	//go:embed templates
	interfaceTemplates embed.FS
)

type (
	interfaceKind string

	Config struct {
		Log     *slog.Logger
		Network *network.Network
		Nics    []*apiv2.MachineNic
		fs      afero.Fs
	}

	loData struct {
		Comment string
		CIDRs   []string
	}

	lanLinkData struct {
		Comment string
		Mac     string
		Index   int
		MTU     int
	}

	lanNetworkData struct {
		Comment  string
		VxlanIDs []uint64
		Index    int
	}

	bridgeNetworkData struct {
		Comment    string
		EVPNIfaces []network.EvpnIface
	}

	bridgeNetdevData struct {
		Comment string
	}

	evpnData struct {
		Comment    string
		EVPNIface  network.EvpnIface
		UnderlayIP string
	}
)

func ConfigureInterfaces(ctx context.Context, cfg *Config) error {
	if err := configureLoopbackInterface(ctx, cfg); err != nil {
		return fmt.Errorf("error configuring loopback interface: %w", err)
	}

	if err := configureLanInterfaces(ctx, cfg); err != nil {
		return fmt.Errorf("error configuring lan interfaces: %w", err)
	}

	if cfg.Network.IsMachine() {
		return nil
	}

	if err := configureBridges(ctx, cfg); err != nil {
		return fmt.Errorf("error configuring network bridges: %w", err)
	}

	if err := configureEVPN(ctx, cfg); err != nil {
		return fmt.Errorf("error configuring evnps: %w", err)
	}

	return nil
}

func configureLoopbackInterface(ctx context.Context, cfg *Config) error {
	loopbackCIDRs, err := cfg.Network.LoopbackCIDRs()
	if err != nil {
		return err
	}

	r, err := renderer.New(&renderer.Config{
		Log:            cfg.Log,
		TemplateString: loNetwork.mustReadTemplate(),
		Data: loData{
			Comment: comment,
			CIDRs:   loopbackCIDRs,
		},
		Fs: cfg.fs,
	})
	if err != nil {
		return err
	}

	_, err = r.Render(ctx, path.Join(systemdNetworkPath, "00-lo.network"))
	if err != nil {
		return err
	}

	return nil
}

func configureLanInterfaces(ctx context.Context, cfg *Config) error {
	const offset = 10

	for idx, nic := range cfg.Nics {
		r, err := renderer.New(&renderer.Config{
			Log:            cfg.Log,
			TemplateString: lanLink.mustReadTemplate(),
			Data: lanLinkData{
				Comment: comment,
				Mac:     nic.Mac,
				Index:   idx,
				MTU:     cfg.Network.MTU(),
			},
			Fs: cfg.fs,
		})
		if err != nil {
			return err
		}

		_, err = r.Render(ctx, path.Join(systemdNetworkPath, fmt.Sprintf("%d-lan%d.link", offset+idx, idx)))
		if err != nil {
			return fmt.Errorf("unable to render lan link config: %w", err)
		}

		r, err = renderer.New(&renderer.Config{
			Log:            cfg.Log,
			TemplateString: lanNetwork.mustReadTemplate(),
			Data: lanNetworkData{
				Comment:  comment,
				VxlanIDs: cfg.Network.VxlanIDs(),
				Index:    idx,
			},
			Fs: cfg.fs,
		})
		if err != nil {
			return err
		}

		_, err = r.Render(ctx, path.Join(systemdNetworkPath, fmt.Sprintf("%d-lan%d.network", offset+idx, idx)))
		if err != nil {
			return fmt.Errorf("unable to render lan network config: %w", err)
		}
	}

	return nil
}

func configureBridges(ctx context.Context, cfg *Config) error {
	const offset = 20

	ifaces, err := cfg.Network.EVPNIfaces()
	if err != nil {
		return fmt.Errorf("unable to get evpn interfaces: %w", err)
	}

	r, err := renderer.New(&renderer.Config{
		Log:            cfg.Log,
		TemplateString: bridgeNetwork.mustReadTemplate(),
		Data: bridgeNetworkData{
			Comment:    comment,
			EVPNIfaces: ifaces,
		},
		Fs: cfg.fs,
	})
	if err != nil {
		return err
	}

	_, err = r.Render(ctx, path.Join(systemdNetworkPath, "20-bridge.network"))
	if err != nil {
		return fmt.Errorf("unable to render bridge network config: %w", err)
	}

	r, err = renderer.New(&renderer.Config{
		Log:            cfg.Log,
		TemplateString: bridgeNetdev.mustReadTemplate(),
		Data: bridgeNetdevData{
			Comment: comment,
		},
		Fs: cfg.fs,
	})
	if err != nil {
		return err
	}

	_, err = r.Render(ctx, path.Join(systemdNetworkPath, "20-bridge.netdev"))
	if err != nil {
		return fmt.Errorf("unable to render bridge netdev config: %w", err)
	}

	return nil
}

func configureEVPN(ctx context.Context, cfg *Config) error {
	const offset = 30

	ifaces, err := cfg.Network.EVPNIfaces()
	if err != nil {
		return fmt.Errorf("unable to get evpn interfaces: %w", err)
	}

	underlayIPs, err := cfg.Network.PrivatePrimaryIPs()
	if err != nil {
		return err
	}

	for idx, iface := range ifaces {
		for _, component := range []struct {
			ikindnetwork interfaceKind
			ikindnetdev  interfaceKind
			name         string
		}{
			{
				ikindnetwork: sviNetwork,
				ikindnetdev:  sviNetdev,
				name:         "svi",
			},
			{
				ikindnetwork: vrfNetwork,
				ikindnetdev:  vrfNetdev,
				name:         "vrf",
			},
			{
				ikindnetwork: vxlanNetwork,
				ikindnetdev:  vxlanNetdev,
				name:         "vxlan",
			},
		} {
			data := evpnData{
				Comment:    comment,
				EVPNIface:  iface,
				UnderlayIP: underlayIPs[0],
			}

			r, err := renderer.New(&renderer.Config{
				Log:            cfg.Log,
				TemplateString: component.ikindnetwork.mustReadTemplate(),
				Data:           data,
				Fs:             cfg.fs,
			})
			if err != nil {
				return err
			}

			_, err = r.Render(ctx, path.Join(systemdNetworkPath, fmt.Sprintf("%d-%s-%d.network", offset+idx, component.name, iface.VrfID)))
			if err != nil {
				return fmt.Errorf("unable to render %s network config: %w", component.name, err)
			}

			r, err = renderer.New(&renderer.Config{
				Log:            cfg.Log,
				TemplateString: component.ikindnetdev.mustReadTemplate(),
				Data:           data,
				Fs:             cfg.fs,
			})
			if err != nil {
				return err
			}

			_, err = r.Render(ctx, path.Join(systemdNetworkPath, fmt.Sprintf("%d-%s-%d.netdev", offset+idx, component.name, iface.VrfID)))
			if err != nil {
				return fmt.Errorf("unable to render %s netdev config: %w", component.name, err)
			}
		}
	}

	return nil
}

func (i interfaceKind) mustReadTemplate() string {
	tpl, err := interfaceTemplates.ReadFile(path.Join("templates", string(i)))
	if err != nil {
		panic(err)
	}

	return string(tpl)
}
