package frr

import (
	"context"
	"fmt"
	"log/slog"
	"net/netip"
	"os/exec"

	"github.com/Masterminds/semver/v3"
	apiv2 "github.com/metal-stack/api/go/metalstack/api/v2"
	"github.com/metal-stack/os-installer/pkg/network"
	systemd_renderer "github.com/metal-stack/os-installer/pkg/systemd-service-renderer"
	renderer "github.com/metal-stack/os-installer/pkg/template-renderer"
	"github.com/spf13/afero"

	_ "embed"
)

const (
	comment = "generated by os-installer"

	serviceName = "frr.service"

	frrConfigPath = "/etc/frr/frr.conf"

	// defaultFrrVersion holds a string that is used in the frr.conf to define the FRR version.
	defaultFrrVersion = "8.5"
	// ipPrefixListSeqSeed specifies the initial value for prefix lists sequence number.
	ipPrefixListSeqSeed = 100
	// ipPrefixListNoExportSuffix defines the suffix to use for private IP ranges that must not be exported.
	ipPrefixListNoExportSuffix = "-no-export"
	// routeMapOrderSeed defines the initial value for route-map order.
	routeMapOrderSeed = 10
)

var (
	//go:embed frr.firewall.tpl
	firewallTemplateString string
	//go:embed frr.machine.tpl
	machineTemplateString string
)

type (
	Config struct {
		Log      *slog.Logger
		Reload   bool
		Validate bool

		Network *network.Network

		FRRVersion *semver.Version

		fs afero.Fs
	}

	// frrData contains attributes to hold FRR configuration of all kind of bare metal servers.
	frrData struct {
		ASN        int64
		Comment    string
		FRRVersion string
		Hostname   string
		RouterID   string
		VRFs       []vrf
	}

	// vrf represents data required to render vrf information into frr.conf.
	vrf struct {
		Comment        string
		ID             uint64
		Table          uint64
		VNI            uint64
		ImportVRFNames []string
		IPPrefixLists  []ipPrefixList
		RouteMaps      []routeMap
		FRRVersion     *frrVersion
	}

	// ipPrefixList represents 'ip prefix-list' filtering mechanism to be used in combination with route-maps.
	ipPrefixList struct {
		Name          string
		Spec          string
		AddressFamily string
		// SourceVRF specifies from which VRF the given prefix list should be imported
		SourceVRF string
	}

	// routeMap represents a route-map to permit or deny routes.
	routeMap struct {
		Name    string
		Entries []string
		Policy  accessPolicy
		Order   int
	}

	frrVersion struct {
		Major uint64
		Minor uint64
	}
)

// Renders renders frr configuration according to the given input data and reloads the service if necessary
func Render(ctx context.Context, cfg *Config) (changed bool, err error) {
	cfg.Log.Debug("render frr configuration")
	var (
		data     any
		template string
	)

	if cfg.Network.IsMachine() {
		net, err := cfg.Network.PrivatePrimaryNetwork()
		if err != nil {
			return false, err
		}
		data = frrData{
			FRRVersion: defaultFrrVersion,
			Hostname:   cfg.Network.Hostname(),
			Comment:    comment,
			ASN:        int64(net.Asn),
			RouterID:   routerID(net),
		}
		template = machineTemplateString
	} else {
		net, err := cfg.Network.UnderlayNetwork()
		if err != nil {
			return false, err
		}
		vrfs, err := assembleVRFs(cfg)
		if err != nil {
			return false, err
		}

		data = frrData{
			FRRVersion: defaultFrrVersion,
			Hostname:   cfg.Network.Hostname(),
			Comment:    comment,
			ASN:        int64(net.Asn),
			RouterID:   routerID(net),
			VRFs:       vrfs,
		}
		template = firewallTemplateString
	}

	r, err := renderer.New(&renderer.Config{
		Log:            cfg.Log,
		TemplateString: template,
		Data:           data,
		Fs:             cfg.fs,
		Validate: func(path string) error {
			if !cfg.Validate {
				return nil
			}

			return validate(path)
		},
	})
	if err != nil {
		return false, err
	}

	changed, err = r.Render(ctx, frrConfigPath)
	if err != nil {
		return changed, err
	}

	if cfg.Reload && changed {
		if err := systemd_renderer.Reload(ctx, cfg.Log, serviceName); err != nil {
			return changed, err
		}
	}

	return
}

// routerID will calculate the bgp router-id which must only be specified in the ipv6 range.
// returns 0.0.0.0 for erroneous ip addresses and 169.254.255.255 for ipv6
// TODO prepare machine allocations with ipv6 primary address and tests
func routerID(net *apiv2.MachineNetwork) string {
	if len(net.Ips) < 1 {
		return "0.0.0.0"
	}
	ip, err := netip.ParseAddr(net.Ips[0])
	if err != nil {
		return "0.0.0.0"
	}
	if ip.Is4() {
		return ip.String()
	}
	return "169.254.255.255"
}

// Validate can be used to run validation on FRR configuration using vtysh.
func validate(frrConfigPath string) error {
	vtysh := fmt.Sprintf("vtysh --dryrun --inputfile %s", frrConfigPath)
	cmd := exec.Command("bash", "-c", vtysh, frrConfigPath)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("vtysh validation failed, output:%s error %w", string(out), err)
	}
	return nil
}

func assembleVRFs(cfg *Config) ([]vrf, error) {
	var (
		result []vrf
		frr    *frrVersion
	)

	if cfg.FRRVersion == nil {
		frrVersion, err := DetectVersion(cfg.Log)
		if err != nil {
			return nil, fmt.Errorf("unable to detect frr version: %w", err)
		}

		cfg.FRRVersion = frrVersion
	}

	frr = &frrVersion{
		Major: cfg.FRRVersion.Major(),
		Minor: cfg.FRRVersion.Minor(),
	}

	for _, n := range cfg.Network.AllocationNetworks() {
		switch n.NetworkType {
		case apiv2.NetworkType_NETWORK_TYPE_UNDERLAY, apiv2.NetworkType_NETWORK_TYPE_SUPER, apiv2.NetworkType_NETWORK_TYPE_SUPER_NAMESPACED:
			continue
		}

		i, err := importRulesForNetwork(cfg, n)
		if err != nil {
			return nil, err
		}

		vrf := vrf{
			ID:             n.Vrf,
			VNI:            n.Vrf,
			ImportVRFNames: i.ImportVRFs,
			IPPrefixLists:  i.prefixLists(),
			RouteMaps:      i.routeMaps(),
			FRRVersion:     frr,
		}
		result = append(result, vrf)
	}

	return result, nil
}
