package frr

import (
	"context"
	"fmt"
	"log/slog"
	"net/netip"

	apiv2 "github.com/metal-stack/api/go/metalstack/api/v2"
	"github.com/metal-stack/os-installer/old/exec"
	"github.com/metal-stack/os-installer/pkg/network"
	systemd_renderer "github.com/metal-stack/os-installer/pkg/systemd-service-renderer"
	renderer "github.com/metal-stack/os-installer/pkg/template-renderer"
	"github.com/spf13/afero"

	_ "embed"
)

const (
	comment = "generated by os-installer"

	serviceName     = "frr.service"
	serviceUnitPath = "/etc/systemd/system/" + serviceName

	frrConfigPath = "/etc/frr/frr.conf"

	// FRRVersion holds a string that is used in the frr.conf to define the FRR version.
	FRRVersion = "8.5"
	// TplFirewallFRR defines the name of the template to render FRR configuration to a 'firewall'.
	TplFirewallFRR = "frr.firewall.tpl"
	// TplMachineFRR defines the name of the template to render FRR configuration to a 'machine'.
	TplMachineFRR = "frr.machine.tpl"
	// IPPrefixListSeqSeed specifies the initial value for prefix lists sequence number.
	IPPrefixListSeqSeed = 100
	// IPPrefixListNoExportSuffix defines the suffix to use for private IP ranges that must not be exported.
	IPPrefixListNoExportSuffix = "-no-export"
	// RouteMapOrderSeed defines the initial value for route-map order.
	RouteMapOrderSeed = 10
	// AddressFamilyIPv4 is the name for this address family for the routing daemon.
	AddressFamilyIPv4 = "ip"
	// AddressFamilyIPv6 is the name for this address family for the routing daemon.
	AddressFamilyIPv6 = "ipv6"
)

var (
	//go:embed frr.firewall.tpl
	firewallTemplateString string
	//go:embed frr.machine.tpl
	machineTemplateString string
)

type (
	Config struct {
		Log      *slog.Logger
		Reload   bool
		Validate bool

		Network *network.Network

		fs afero.Fs
	}

	// CommonFRRData contains attributes that are common to FRR configuration of all kind of bare metal servers.
	CommonFRRData struct {
		ASN        int64
		Comment    string
		FRRVersion string
		Hostname   string
		RouterID   string
	}

	// MachineFRRData contains attributes required to render frr.conf of bare metal servers that function as 'machine'.
	MachineFRRData struct {
		CommonFRRData
	}

	// FirewallFRRData contains attributes required to render frr.conf of bare metal servers that function as 'firewall'.
	FirewallFRRData struct {
		CommonFRRData
		VRFs []VRF
	}

	// VRF represents data required to render VRF information into frr.conf.
	VRF struct {
		Comment        string
		ID             uint64
		Table          uint64
		VNI            uint64
		ImportVRFNames []string
		IPPrefixLists  []IPPrefixList
		RouteMaps      []RouteMap
		FRRVersion     *FRR
	}

	// IPPrefixList represents 'ip prefix-list' filtering mechanism to be used in combination with route-maps.
	IPPrefixList struct {
		Name          string
		Spec          string
		AddressFamily *apiv2.NetworkAddressFamily
		// SourceVRF specifies from which VRF the given prefix list should be imported
		SourceVRF string
	}
	// RouteMap represents a route-map to permit or deny routes.
	RouteMap struct {
		Name    string
		Entries []string
		Policy  string
		Order   int
	}

	FRR struct {
		Major uint64
		Minor uint64
	}
)

// Renders renders frr configuration according to the given input data and reloads the service if necessary
func Render(ctx context.Context, cfg *Config) (changed bool, err error) {
	var (
		data     any
		template string
	)

	if cfg.Network.IsMachine() {
		net, err := cfg.Network.PrivatePrimaryNetwork()
		if err != nil {
			return false, err
		}
		data = MachineFRRData{
			CommonFRRData: CommonFRRData{
				FRRVersion: FRRVersion,
				Hostname:   cfg.Network.Hostname(),
				Comment:    comment,
				ASN:        int64(net.Asn),
				RouterID:   routerID(net),
			},
		}
		template = machineTemplateString
	} else {
		net, err := cfg.Network.UnderlayNetwork()
		if err != nil {
			return false, err
		}
		vrfs, err := assembleVRFs(cfg)
		if err != nil {
			return false, err
		}

		data = FirewallFRRData{
			CommonFRRData: CommonFRRData{
				FRRVersion: FRRVersion,
				Hostname:   cfg.Network.Hostname(),
				Comment:    comment,
				ASN:        int64(net.Asn),
				RouterID:   routerID(net),
			},
			VRFs: vrfs,
		}
		template = firewallTemplateString
	}

	r, err := renderer.New(&renderer.Config{
		Log:            cfg.Log,
		TemplateString: template,
		Data:           data,
		Fs:             cfg.fs,
	})
	if err != nil {
		return false, err
	}

	changed, err = r.Render(ctx, frrConfigPath)
	if err != nil {
		return changed, err
	}

	if cfg.Validate {
		if err := validate(frrConfigPath); err != nil {
			return changed, err
		}
	}

	if cfg.Reload && changed {
		if err := systemd_renderer.Reload(ctx, cfg.Log, serviceName); err != nil {
			return changed, err
		}
	}

	return
}

// routerID will calculate the bgp router-id which must only be specified in the ipv6 range.
// returns 0.0.0.0 for erroneous ip addresses and 169.254.255.255 for ipv6
// TODO prepare machine allocations with ipv6 primary address and tests
func routerID(net *apiv2.MachineNetwork) string {
	if len(net.Ips) < 1 {
		return "0.0.0.0"
	}
	ip, err := netip.ParseAddr(net.Ips[0])
	if err != nil {
		return "0.0.0.0"
	}
	if ip.Is4() {
		return ip.String()
	}
	return "169.254.255.255"
}

// Validate can be used to run validation on FRR configuration using vtysh.
func validate(frrConfigPath string) error {
	vtysh := fmt.Sprintf("vtysh --dryrun --inputfile %s", frrConfigPath)

	return exec.NewVerboseCmd("bash", "-c", vtysh, frrConfigPath).Run()
}

func assembleVRFs(cfg *Config) ([]VRF, error) {
	var (
		result []VRF
		frr    *FRR
	)

	// FIXME do we need to support older frr versions <9
	// if frrVersion != nil {
	// 	frr = &FRR{
	// 		Major: frrVersion.Major(),
	// 		Minor: frrVersion.Minor(),
	// 	}
	// }

	for _, n := range cfg.Network.AllocationNetworks() {
		switch n.NetworkType {
		case apiv2.NetworkType_NETWORK_TYPE_UNDERLAY, apiv2.NetworkType_NETWORK_TYPE_SUPER, apiv2.NetworkType_NETWORK_TYPE_SUPER_NAMESPACED:
			continue
		}

		i, err := importRulesForNetwork(cfg, n)
		if err != nil {
			return nil, err
		}
		vrf := VRF{
			ID:             n.Vrf,
			VNI:            n.Vrf,
			ImportVRFNames: i.ImportVRFs,
			IPPrefixLists:  i.prefixLists(),
			RouteMaps:      i.routeMaps(),
			FRRVersion:     frr,
		}
		result = append(result, vrf)
	}

	return result, nil
}
