package oscommon

import (
	"context"
	"fmt"
)

const (
	EtcHostsPath        = "/etc/hosts"
	etcHostsFileContent = `# this file was auto generated by the os-installer
127.0.0.1        localhost
%s        %s
`
)

func (d *CommonTasks) WriteHosts(ctx context.Context) error {
	ips, err := d.network.PrivatePrimaryIPs()
	if err != nil {
		return err
	}

	return d.fs.WriteFile(EtcHostsPath, fmt.Appendf(nil, etcHostsFileContent, ips[0], d.allocation.Hostname), 0644)
}
